apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-env
  namespace: dbrf
data:
  CONNECT_BOOTSTRAP_SERVERS: "kafka-headless.dbrf.svc.cluster.local:9092" # But if both Kafka Connect and Kafka are in the same namespace, you can simply use: kafka:9092
  CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
  CONNECT_GROUP_ID: "connect-group"
  CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
  CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
  CONNECT_REST_PORT: "8083"
  CONNECT_PRODUCER_MAX_REQUEST_SIZE: "16777216"
