apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
  namespace: dbrf
spec:
  type: NodePort
  selector:
    app: flink-sql-gateway
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
      nodePort: 30083
