apiVersion: v1
kind: Service
metadata:
  name: conduktor-console
  namespace: dbrf
spec:
  selector:
    app: conduktor-console
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
