apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: dbrf
spec:
  clusterIP: None # Headless service required for StatefulSet
  selector:
    app: schema-registry
  ports:
    - port: 8081
      targetPort: 8081
