apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  namespace: dbrf
spec:
  serviceName: schema-registry
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.4.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              # value: "PLAINTEXT://broker-kafka:29092"
              value: "PLAINTEXT://kafka-headless:9092"
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
