apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: conduktor-db
  namespace: dbrf
spec:
  serviceName: conduktor-db
  replicas: 1
  selector:
    matchLabels:
      app: conduktor-db
  template:
    metadata:
      labels:
        app: conduktor-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "conduktor_console"
            - name: POSTGRES_USER
              value: "conduktor"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "scram-sha-256"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          hostPath:
            path: /etc/conduktor-db # 👈 Adjust to your host path
            type: DirectoryOrCreate
