apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-headless
  namespace: dbrf
spec:
  clusterIP: None
  selector:
    app: flink-taskmanager
  ports:
    - port: 6122
      targetPort: 6122
