apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: dbrf
spec:
  type: NodePort
  selector:
    app: flink-jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: web-ui
      port: 8081
      targetPort: 8081
      nodePort: 30881
    - name: sql-gateway
      port: 8083
      targetPort: 8083
      nodePort: 30999
