---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-conf
  namespace: dbrf
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 30
    taskmanager.memory.process.size: 2048m
    s3.access-key: minioadmin
    s3.access-secret: minioadmin
    s3.endpoint: http://minio:9000
    s3.path.style.access: true
    execution.checkpointing.interval: 10000
    execution.checkpointing.mode: AT_LEAST_ONCE
    execution.checkpointing.timeout: 10min
    state.backend: rocksdb
    state.backend.incremental: true
    state.checkpoints.dir: s3a://dbrf-bucket/checkpoints/
    state.savepoints.dir: s3a://dbrf-bucket/savepoints/
    restart-strategy.type: exponential-delay
    env.java.opts: -Dlog4j.configuration=file:/opt/flink/conf/log4j.properties
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN">
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="INFO">
          <AppenderRef ref="Console"/>
        </Root>
      </Loggers>
    </Configuration>
