apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: dbrf
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: kafka
      containers:
        - name: kafka
          image: docker.io/confluentinc/confluent-local:7.5.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -exc
            - |
              export CLUSTER_ID="6PMpHYL9QkeyXRj9Nrp4KA" && \
              export KAFKA_NODE_ID=${HOSTNAME##*-} \
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.kafka-headless.dbrf.svc.cluster.local:9092 \
              export KAFKA_CONTROLLER_QUORUM_VOTERS="0@kafka-0.kafka-headless.dbrf.svc.cluster.local:29093,1@kafka-1.kafka-headless.dbrf.svc.cluster.local:29093,2@kafka-2.kafka-headless.dbrf.svc.cluster.local:29093" \

              exec /etc/confluent/docker/run
          env:
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9092
              name: tcp-kafka-int
            - containerPort: 29093
              name: tcp-kafka-ctrl
          resources:
            limits:
              cpu: "1"
              memory: 1400Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/kafka
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: config
  updateStrategy:
    type: RollingUpdate
